// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Lt_VUFUj_O1PtX8AqPKu2nGE91uh4oo',
    appId: '1:989355286850:web:5584d0d253d3ceaf2768db',
    messagingSenderId: '989355286850',
    projectId: 'cmp-project-1b822',
    authDomain: 'cmp-project-1b822.firebaseapp.com',
    storageBucket: 'cmp-project-1b822.firebasestorage.app',
    measurementId: 'G-16ZR6WM9X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UmqyzaLrHafkuGd1e6V4XBiBezGMgrc',
    appId: '1:989355286850:android:04fdb9a520e798bd2768db',
    messagingSenderId: '989355286850',
    projectId: 'cmp-project-1b822',
    storageBucket: 'cmp-project-1b822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFqlHpM6YZbT1_A1gUD6cF53Kr-bsKjE0',
    appId: '1:989355286850:ios:18bc485c918aa58f2768db',
    messagingSenderId: '989355286850',
    projectId: 'cmp-project-1b822',
    storageBucket: 'cmp-project-1b822.firebasestorage.app',
    iosBundleId: 'com.coffeeshop.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFqlHpM6YZbT1_A1gUD6cF53Kr-bsKjE0',
    appId: '1:989355286850:ios:18bc485c918aa58f2768db',
    messagingSenderId: '989355286850',
    projectId: 'cmp-project-1b822',
    storageBucket: 'cmp-project-1b822.firebasestorage.app',
    iosBundleId: 'com.coffeeshop.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Lt_VUFUj_O1PtX8AqPKu2nGE91uh4oo',
    appId: '1:989355286850:web:2d271d6e01e37c372768db',
    messagingSenderId: '989355286850',
    projectId: 'cmp-project-1b822',
    authDomain: 'cmp-project-1b822.firebaseapp.com',
    storageBucket: 'cmp-project-1b822.firebasestorage.app',
    measurementId: 'G-HL4WFM3YPB',
  );
}
